CREATE TABLE IF NOT EXISTS ship_location (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	name varchar UNIQUE NOT NULL,
	x_coordinate DOUBLE PRECISION NOT NULL,
	y_coordinate DOUBLE PRECISION NOT NULL,
	CONSTRAINT ship_location_pkey PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS ship_location_index_1 ON ship_location (name);

CREATE TABLE IF NOT EXISTS imperial_cargo_ship (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	name varchar UNIQUE NOT NULL,
	distance DOUBLE PRECISION NOT NULL,
	message varchar NOT NULL,
	ip_address varchar NOT NULL,
	CONSTRAINT imperial_cargo_ship_pkey PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS imperial_cargo_ship_index_1 ON imperial_cargo_ship (name);

CREATE TABLE IF NOT EXISTS users (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	username varchar UNIQUE NOT NULL,
	password varchar NOT NULL,
	CONSTRAINT users_pkey PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS users_index_1 ON users (username, password);

CREATE TABLE IF NOT EXISTS roles (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	name varchar NOT NULL,
	CONSTRAINT roles_pkey PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS roles_index_1 ON roles (name);

CREATE TABLE IF NOT EXISTS users_roles (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	user_id int8 NOT NULL,
	role_id int8 NOT NULL,
	CONSTRAINT users_roles_pkey PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS users_roles_index_1 ON users_roles (user_id, role_id);




