CREATE TABLE IF NOT EXISTS ship_location (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	name varchar UNIQUE NOT NULL,
	x_coordinate DOUBLE PRECISION NOT NULL,
	y_coordinate DOUBLE PRECISION NOT NULL,
	CONSTRAINT ship_location_pkey PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS ship_location_index_1 ON ship_location (name);

CREATE TABLE IF NOT EXISTS imperial_cargo_ship (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	name varchar UNIQUE NOT NULL,
	distance DOUBLE PRECISION NOT NULL,
	message varchar NOT NULL,
	ip varchar NOT NULL,
	CONSTRAINT imperial_cargo_ship_pkey PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS imperial_cargo_ship_index_1 ON imperial_cargo_ship (name);